sudo: required

services:
  - docker

before_script:
  - docker build -t amila/docker-react -f Dockerfile.dev .

script:
  - docker run amila/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-840888876496"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_kay: "AWS_SECRET_KEY"


